#!/usr/bin/env bash

GOOGLE_CREDENTIALS="$(get-k8s-concourse-secret stress-tests gcs key)" \
fly --target ci \
    execute \
    --include-ignored \
    --config pipeline/tasks/update-website.yml \
    --input results=./results
