#!/usr/bin/env bash

GOOGLE_CREDENTIALS="$(bo show credential concourse-main stress-tests.gcs key)" \
fly --target ci \
    execute \
    --include-ignored \
    --config pipeline/tasks/update-website.yml \
    --input results=./results
