#!/usr/bin/env bash

set -e

cwd="$(cd "$(dirname "$0")" && pwd)"

NUMBER_OF_THREADS=100
RAMP_UP_TIME=1
STRESS_TEST_CLIENT_SECRET="$(bo show credential concourse-main stress-test.credentials client_secret)"
STRESS_TEST_CLIENT_ID="$(bo show credential concourse-main stress-test.credentials client_id)"

export NUMBER_OF_THREADS
export RAMP_UP_TIME
export STRESS_TEST_CLIENT_SECRET
export STRESS_TEST_CLIENT_ID

fly --target ci \
    execute \
    --config "$cwd/pipeline/tasks/run.yaml" \
    --input source="$cwd" \
    --output results=results
