#!/usr/bin/env bash

set -e

cwd="$(cd "$(dirname "$0")" && pwd)"

NUMBER_OF_THREADS=100
RAMP_UP_TIME=1
STRESS_TEST_USERNAME="$(get-k8s-concourse-secret stress-tests credentials username)"
STRESS_TEST_PASSWORD="$(get-k8s-concourse-secret stress-tests credentials password)"

export NUMBER_OF_THREADS
export RAMP_UP_TIME
export STRESS_TEST_USERNAME
export STRESS_TEST_PASSWORD

fly --target ci \
    execute \
    --config "$cwd/pipeline/tasks/run.yml" \
    --input source="$cwd" \
    --output results=results
