#!/usr/bin/env bash

set -e

cwd="$(cd "$(dirname "$0")" && pwd)"
threads=$1
HEAP="-Xms4g -Xmx4g -XX:MaxMetaspaceSize=4096m"

if [ -z "$threads" ]
then
    echo "Usage: $(basename "$0") THREADS"
    exit 1
fi

mkdir -p /tmp/webreports
rm -rf /tmp/webreports*

export HEAP
jmeter \
    -n \
    -t "$cwd/partial-login-teachers-boclips.jmx" \
    -l /tmp/webreports.log \
    -e \
    -o /tmp/webreports/ \
    -Jthreads="$threads"
