#!/usr/bin/env bash

set -e

cwd="$(cd "$(dirname "$0")" && pwd)"

journey=$1
threads=$2
ramp_up=$3
HEAP="-Xms8g -Xmx16g -XX:MaxMetaspaceSize=256m"
export HEAP

if [ -z "$threads" ] || [ -z "$ramp_up" ]
then
    echo "Usage: $(basename "$0") JOURNEY THREADS DELAY_THREAD_START"
    echo "Where THREADS is number of users and RAMP_UP is the time" \
        "in seconds it takes to start all the threads."
    exit 1
fi

mkdir -p /tmp/webreports
rm -rf /tmp/webreports*

cmd="jmeter \
    -n \
    -t "$cwd/$journey" \
    -l /tmp/webreports.log \
    -e \
    -o /tmp/webreports/ \
    -Jthreads=$threads \
    -Jramp_up=$ramp_up
"

echo "$cmd"

$cmd

echo "To check results: open /tmp/webreports/index.html"
