#!/usr/bin/env bash

set -e

cwd="$(cd "$(dirname "$0")" && pwd)"
threads=$1
ramp_up=$2
HEAP="-Xms4g -Xmx4g -XX:MaxMetaspaceSize=4096m"

if [ -z "$threads" ] || [ -z "$ramp_up" ]
then
    echo "Usage: $(basename "$0") THREADS DELAY_THREAD_START"
    echo "Where THREADS is number of users and RAMP_UP is the time" \
        "in seconds it takes to start all the threads."
    exit 1
fi

mkdir -p /tmp/webreports
rm -rf /tmp/webreports*

cmd="jmeter \
    -n \
    -t "$cwd/api.jmx" \
    -l /tmp/webreports.log \
    -e \
    -o /tmp/webreports/ \
    -Jthreads=$threads \
    -Jramp_up=$ramp_up"

echo "$cmd"
export HEAP
$cmd
echo "To check results: open /tmp/webreports/index.html"