---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: justb4/jmeter
    tag: 5.1.1

inputs:
- name: source

outputs:
- name: results

params:
  NUMBER_OF_THREADS:
  RAMP_UP_TIME:
  STRESS_TEST_CLIENT_ID:
  STRESS_TEST_CLIENT_SECRET:

run:
  path: source/pipeline/scripts/run
