---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: google/cloud-sdk
    tag: 272.0.0-alpine

inputs:
- name: results

params:
  GOOGLE_CREDENTIALS:

run:
  path: bash
  args:
  - -ec
  - |-
    gcloud auth application-default login
    gsutil \
      -m \
      -h "Cache-Control:no-cache,max-age=0" \
      rsync \
      -a public-read \
      -d \
      -r \
      ./results/webreports/ \
      gs://stress-tests.devboclips.net
