---
jobs:
- name: stress-tests
  plan:
  - get: source
    resource: stress-tests
  - get: every-24h
    trigger: true
  - task: run
    file: source/pipeline/tasks/run.yaml
    params:
      NUMBER_OF_THREADS: 300
      RAMP_UP_TIME: 60
      STRESS_TEST_USERNAME: ((credentials.username))
      STRESS_TEST_PASSWORD: ((credentials.password))
  - task: update-website
    file: source/pipeline/tasks/update-website.yaml
    params:
      GOOGLE_CREDENTIALS: ((gcs.key))

resources:
- name: stress-tests
  type: git
  icon: github-circle
  source:
    branch: master
    uri: https://github.com/boclips/stress-tests.git

- name: every-24h
  type: time
  icon: clock-outline
  source:
    interval: 24h
