---
meta:
  update_website:
    &update_website
    task: update-website
    file: source/pipeline/tasks/update-website.yaml
    params:
      GOOGLE_CREDENTIALS: ((gcs.key))

jobs:
- name: slam
  serial_groups: [stress]
  plan:
  - get: source
    resource: stress-tests
  - task: run
    file: source/pipeline/tasks/run.yaml
    params:
      NUMBER_OF_THREADS: 800
      RAMP_UP_TIME: 2
      STRESS_TEST_CLIENT_ID: ((credentials.client_id))
      STRESS_TEST_CLIENT_SECRET: ((credentials.client_secret))
  - *update_website

- name: slow-burn
  serial_groups: [stress]
  plan:
  - get: source
    resource: stress-tests
  - get: every-24h
    trigger: true
  - task: run
    file: source/pipeline/tasks/run.yaml
    params:
      NUMBER_OF_THREADS: 2000
      RAMP_UP_TIME: 30
      STRESS_TEST_CLIENT_ID: ((credentials.client_id))
      STRESS_TEST_CLIENT_SECRET: ((credentials.client_secret))
  - *update_website

resources:
- name: stress-tests
  type: git
  icon: github-circle
  source:
    branch: master
    uri: https://github.com/boclips/stress-tests.git

- name: every-24h
  type: time
  icon: clock-outline
  source:
    interval: 24h
