#!/usr/bin/env bash

if [[ -z "$NUMBER_OF_THREADS" ]]
then
    echo "Missing NUMBER_OF_THREADS"
    exit 1
fi

if [[ -z "$RAMP_UP_TIME" ]]
then
    echo "Missing RAMP_UP_TIME"
    exit 1
fi

if [[ -z "$STRESS_TEST_CLIENT_ID" ]]
then
    echo "Missing STRESS_TEST_CLIENT_ID"
    exit 1
fi

if [[ -z "$STRESS_TEST_CLIENT_SECRET" ]]
then
    echo "Missing STRESS_TEST_CLIENT_SECRET"
    exit 1
fi

(
cd ./source || exit 1
./run-stress-tests as-api-integration.jmx "$NUMBER_OF_THREADS" "$RAMP_UP_TIME"
)

cp -R /tmp/webreports results/
cp /tmp/webreports.log results/
