#!/usr/bin/env bash

set -x

if [[ -z "$NUMBER_OF_THREADS" ]]
then
    echo "Missing NUMBER_OF_THREADS"
    exit 1
fi

if [[ -z "$RAMP_UP_TIME" ]]
then
    echo "Missing RAMP_UP_TIME"
    exit 1
fi

if [[ -z "$STRESS_TEST_USERNAME" ]]
then
    echo "Missing STRESS_TEST_USERNAME"
    exit 1
fi

if [[ -z "$STRESS_TEST_PASSWORD" ]]
then
    echo "Missing STRESS_TEST_PASSWORD"
    exit 1
fi

(
cd ./source || exit 1
./run-stress-tests "$NUMBER_OF_THREADS" "$RAMP_UP_TIME"
)

cp -R /tmp/webreports results/
cp /tmp/webreports.log results/
